import React,{useState} from 'react';
import {CalendarDays,Users,Link2,ArrowUpRight,Scissors,Check,Search} from 'lucide-react';
import {siteData} from '../data/siteData';
import {professionals} from '../data/professionals';
import {STORAGE_KEY,localDate,demoServices,statuses,availableSlots,seedData} from '../data/demoStore';
import '../styles/demo.css';
export default function DemoStudio(){
 const [data,setData]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved&&Array.isArray(saved.clients)&&Array.isArray(saved.appointments)&&saved.clients.every(c=>typeof c.name==='string')&&saved.appointments.every(a=>statuses.includes(a.status)&&demoServices.some(s=>s.id===a.serviceId)))return saved;}catch{}return seedData()});
 const [tab,setTab]=useState('Agenda'),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[statusFilter,setStatusFilter]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(null);
 const [serviceId,setService]=useState('corte'),[professional,setProfessional]=useState('Gustavo'),[date,setDate]=useState(localDate()),[time,setTime]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState('');
 const service=demoServices.find(s=>s.id===serviceId);
 const save=next=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setData(next);return true;}catch{setNotice('Não foi possível salvar. Libere o armazenamento do navegador e tente novamente.');return false;}};
 const slots=availableSlots(data.appointments,date,professional,service.duration);
 const client=id=>data.clients.find(c=>c.id===id);
 function book(e){e.preventDefault();if(!name.trim()||!/^\d{10,11}$/.test(phone.replace(/\D/g,''))){setNotice('Informe o nome e um telefone com DDD (10 ou 11 dígitos).');return;}if(!availableSlots(data.appointments,date,professional,service.duration).includes(time)){setNotice('Escolha um horário disponível.');return;}
 const normalized=phone.replace(/\D/g,'');const existing=data.clients.find(c=>c.phone===normalized);const person=existing||{id:crypto.randomUUID(),name:name.trim(),phone:normalized,notes:''};
 const appointment={id:crypto.randomUUID(),clientId:person.id,serviceId,professional,date,time,start:Number(time.slice(0,2))*60+Number(time.slice(3)),duration:service.duration,status:'Solicitado'};
 if(save({clients:existing?data.clients:[...data.clients,person],appointments:[...data.appointments,appointment]})){setNotice('Solicitação de demonstração salva! Confira o atendimento na Agenda e o cadastro em Clientes. Nenhuma reserva real foi criada.');setTime('');setName('');setPhone('');}}
 function updateStatus(a,status){if(status!=='Cancelado'&&a.status==='Cancelado'&&!availableSlots(data.appointments,a.date,a.professional,a.duration,a.id).includes(a.time)){setNotice('Este horário não está mais disponível. Crie um novo agendamento.');return;}save({...data,appointments:data.appointments.map(r=>r.id===a.id?{...r,status}:r)});}
 const appointments=data.appointments.filter(a=>(!filter||a.date===filter)&&(!statusFilter||a.status===statusFilter)&&`${client(a.clientId)?.name} ${a.professional}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
 return <div className="demo"><aside className="demo-sidebar"><a href="/"><img src={siteData.images.logoHorizontal} alt="Studio Clean"/></a><p className="demo-kicker">ESPAÇO DE GESTÃO</p><nav aria-label="Demonstração">{[['Agenda',CalendarDays],['Clientes',Users],['Agendar',Scissors],['Conexões',Link2]].map(([label,Icon])=><button key={label} aria-current={tab===label?'page':undefined} onClick={()=>{setTab(label);setSearch('');setNotice('')}}><Icon size={19}/>{label}</button>)}</nav><div className="demo-sidebar-bottom"><span className="demo-dot"/> Ambiente de apresentação<p>Uma experiência conectada, do primeiro contato ao próximo cuidado.</p><a href="/">Ver site do studio <ArrowUpRight size={16}/></a></div></aside>
 <main className="demo-main"><div className="demo-banner"><span>DEMONSTRAÇÃO</span> Dados fictícios e locais. Use apenas dados de teste. Reservas e mensagens não são enviadas.</div><header className="demo-heading"><div><p className="demo-kicker">STUDIO CLEAN · BARBER & BEAUTY</p><h1>{tab==='Agenda'?'Cada cuidado, no seu tempo.':tab==='Clientes'?'Boas relações começam aqui.':tab==='Agendar'?'Seu próximo momento.':'Tudo começa com uma conexão.'}</h1><p>{tab==='Agenda'?'Sua agenda e os próximos atendimentos em um só lugar.':tab==='Clientes'?'Histórico, preferências e atenção a cada cliente.':tab==='Agendar'?'Experimente a jornada de reserva integrada ao CRM.':'Veja o que já pode ser apresentado e o que falta ativar.'}</p></div>{tab!=='Agendar'&&<button className="demo-primary" onClick={()=>setTab('Agendar')}>+ Novo agendamento</button>}</header>
 {notice&&<div className="demo-notice" role="status">{notice}</div>}
 {tab==='Agenda'&&<><div className="demo-metrics">{[['Atendimentos hoje',data.appointments.filter(a=>a.date===localDate()&&a.status!=='Cancelado').length],['Aguardando confirmação',data.appointments.filter(a=>a.status==='Solicitado').length],['Clientes cadastrados',data.clients.length]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value.toString().padStart(2,'0')}</strong></article>)}</div><section className="demo-panel"><div className="demo-panel-title"><h2>Agenda de atendimentos</h2><span>Horário local do navegador</span></div><div className="demo-filters"><label><Search size={16}/><input aria-label="Buscar atendimento" placeholder="Cliente ou profissional" value={search} onChange={e=>setSearch(e.target.value)}/></label><input aria-label="Filtrar por data" type="date" value={filter} onChange={e=>setFilter(e.target.value)}/><select aria-label="Filtrar por status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos os status</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>{setSearch('');setFilter('');setStatusFilter('')}}>Limpar filtros</button></div><div className="demo-table-wrap"><table><thead><tr><th>Dia e hora</th><th>Cliente / serviço</th><th>Profissional</th><th>Situação</th></tr></thead><tbody>{appointments.map(a=><tr key={a.id}><td><strong>{a.time}</strong><small>{a.date.split('-').reverse().join('/')}</small></td><td><button className="demo-client-link" onClick={()=>{setSelected(a.clientId);setSearch('');setTab('Clientes')}}>{client(a.clientId)?.name||'Cliente'}</button><small>{demoServices.find(s=>s.id===a.serviceId)?.name} · {a.duration} min</small></td><td>{a.professional}</td><td><select className={`demo-status status-${a.status}`} aria-label={`Situação de ${client(a.clientId)?.name}`} value={a.status} onChange={e=>updateStatus(a,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table>{!appointments.length&&<p className="demo-empty">Nenhum atendimento encontrado. Escolha outra data ou crie um agendamento.</p>}</div></section></>}
 {tab==='Agendar'&&<div className="demo-book-grid"><form className="demo-panel demo-form" onSubmit={book}><h2>Reserve um tempo para você</h2><p>Serviços e durações ilustrativos para esta apresentação.</p><label>01 · Seu cuidado<select value={serviceId} onChange={e=>{const s=demoServices.find(s=>s.id===e.target.value);setService(s.id);setProfessional(s.professionals[0]);setTime('')}}>{demoServices.map(s=><option key={s.id} value={s.id}>{s.name} · {s.duration} min</option>)}</select></label><fieldset><legend>02 · Quem vai cuidar de você?</legend><div className="demo-professionals">{professionals.filter(p=>service.professionals.includes(p.name)).map(p=><button type="button" key={p.name} aria-pressed={professional===p.name} onClick={()=>{setProfessional(p.name);setTime('')}}><img src={p.photo} alt=""/><span>{p.name}</span></button>)}</div></fieldset><label>03 · Qual dia?<input type="date" required min={localDate()} value={date} onChange={e=>{setDate(e.target.value);setTime('')}}/></label><fieldset><legend>Horários disponíveis na demonstração</legend><div className="demo-slots">{slots.map(t=><button type="button" key={t} aria-pressed={time===t} onClick={()=>setTime(t)}>{t}</button>)}</div>{!slots.length&&<p>Sem horários neste dia. Escolha outra data.</p>}</fieldset><div className="demo-fields"><label>Nome de teste<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Cliente de teste"/></label><label>Telefone de teste com DDD<input type="tel" required maxLength={16} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(61) 99999-0000"/></label></div><button className="demo-primary" disabled={!time} type="submit">Solicitar agendamento de teste <ArrowUpRight size={18}/></button></form><aside className="demo-summary"><span className="demo-kicker">UM MOMENTO SÓ SEU</span><h2>Seu estilo.<br/>Seu cuidado.<br/><em>Seu momento.</em></h2><hr/><h3>{service.name}</h3><p>Com {professional} · {service.duration} minutos</p><p>{date?date.split('-').reverse().join('/'):'Escolha uma data'}{time&&` às ${time}`}</p><div><Check size={18}/> Cadastro automático no CRM</div><div><Check size={18}/> Controle de horários por profissional</div><small>A confirmação nesta demonstração acontece pela tela Agenda. Não representa disponibilidade do Trinks.</small></aside></div>}
 {tab==='Clientes'&&<section className="demo-panel"><div className="demo-panel-title"><h2>Relacionamento com clientes</h2><span>{data.clients.length} cadastros</span></div><input className="demo-search" aria-label="Buscar cliente" placeholder="Buscar por nome ou telefone" value={search} onChange={e=>setSearch(e.target.value)}/><div className="demo-clients">{data.clients.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(search.toLowerCase())).map(c=><article key={c.id} className={selected===c.id?'is-selected':''}><div className="demo-avatar">{c.name.slice(0,1)}</div><h3>{c.name}</h3><p>{c.phone||'Cadastro fictício · sem telefone'}</p><label>Preferências e observações<textarea aria-label={`Observações de ${c.name}`} maxLength={1000} value={c.notes} onChange={e=>save({...data,clients:data.clients.map(p=>p.id===c.id?{...p,notes:e.target.value}:p)})}/></label><h4>Histórico de atendimentos</h4>{data.appointments.filter(a=>a.clientId===c.id).sort((a,b)=>b.date.localeCompare(a.date)).map(a=><p className="demo-history" key={a.id}><strong>{demoServices.find(s=>s.id===a.serviceId)?.name}</strong><small>{a.date.split('-').reverse().join('/')} · {a.time} · {a.professional}<br/>{a.status}</small></p>)}</article>)}</div>{!data.clients.some(c=>`${c.name} ${c.phone}`.toLowerCase().includes(search.toLowerCase()))&&<p className="demo-empty">Nenhum cliente encontrado.</p>}</section>}
 {tab==='Conexões'&&<div className="demo-connections">{[['Trinks','Aguardando acesso','O site já abre a agenda oficial. A sincronização do CRM exige acesso à API, identificação do estabelecimento e validação dos serviços e profissionais.'],['WhatsApp','Atendimento manual no site','O site prepara a mensagem para a recepção. Lembretes automáticos dependem da contratação e configuração de um provedor de WhatsApp.'],['Google Agenda','A configurar','A conexão ainda não está ativa. Precisamos definir a conta, autorizar o acesso e combinar quais agendas serão sincronizadas.']].map(([title,status,description])=><article className="demo-panel" key={title}><Link2/><h2>{title}</h2><span className="demo-connection-status">{status}</span><p>{description}</p></article>)}<section className="demo-panel demo-next"><h2>Da apresentação à operação</h2><p>Validar regras e durações com a loja, liberar os acessos, implantar banco de dados e login da equipe e testar reservas, cancelamentos e sincronização antes da ativação.</p><p>Esta demonstração salva os testes somente neste navegador. Não é um painel privado nem um CRM de produção.</p><button onClick={()=>{if(window.confirm('Apagar os testes deste navegador e restaurar os exemplos?')){if(save(seedData())){setSelected(null);setNotice('Exemplos restaurados.');}}}}>Restaurar dados de exemplo</button></section></div>}
 </main></div>
}

